name: Docker

on:

  release:
    types: [published]

  push:
    # Publish `master` as Docker `master-latest` image
    # Publish for any branch as well
    branches:
      - master
      - '*'

    # Publish `v1.2.3` tags as releases.
    tags:
      - 'v*'

  # Run tests for any PRs.
  pull_request:


env:
  # TODO: Change variable to your image's name.
  IMAGE: demo-app
  REGISTRY: docker.io/mk51

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: docker build .

  # Push image to Docker Hub
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build -t $IMAGE .

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USER }}" --password "${{ secrets.DOCKER_PASS }}"


      - name: Push image for master branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          VERSION=${GITHUB_SHA}

          echo IMAGE=$IMAGE
          echo VERSION=$VERSION

          docker tag "$IMAGE" "$REGISTRY/$IMAGE:$VERSION"
          docker push "$REGISTRY/$IMAGE:$VERSION"

      - name: Replace image tag in deployment
        run: sed -E -i  "s/(.*demo-app:).*/\1${GITHUB_SHA}/" deployment.yml

      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh }}
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updating deployment with tag ${GITHUB_SHA}"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master
        
